planMessage = (
    "<b>🎉 Welcome to DRM Level 1 Bot! 🎉</b>\n\n"
    "<b><i>You can have access to download all Non-DRM+AES Encrypted URLs 🔐 including:</i></b>\n\n"
    f"<blockquote>"
    f"   • 📚 <b>Appx Zip+Encrypted Url</b>\n"
    f"   • 🎓 <b>Classplus DRM+ NDRM</b>\n"
    f"   • 🧑‍🏫 <b>PhysicsWallah DRM</b>\n"
    f"   • 📚 <b>CareerWill + PDF</b>\n"
    f"   • 🎓 <b>Khan GS</b>\n"
    f"   • 🎓 <b>Study Iq DRM</b>\n"
    f"   • 🚀 <b>APPX + APPX Enc PDF</b>\n"
    f"   • 🎓 <b>Vimeo Protection</b>\n"
    f"   • 🎓 <b>Brightcove Protection</b>\n"
    f"   • 🎓 <b>Visionias Protection</b>\n"
    f"   • 🎓 <b>Zoom Video</b>\n"
    f"   • 🎓 <b>Utkarsh Protection(Video + PDF)</b>\n"
    f"   • 🎓 <b>All Non DRM+AES Encrypted URLs</b>\n"
    f"   • 🎓 <b>MPD URLs if the key is known (e.g., Mpd_url?key=--key XX:XX)</b>\n"
    f"</blockquote>\n\n"
    "<b>🚀 You are not subscribed to any plan yet!</b>\n\n"
    "<blockquote><b><i>💵 Monthly Plan: ₹ 1200</i></b></blockquote>\n"
    "<b><i>If you want to buy membership of the bot, feel free to contact the Bot Admin.</i></b>"
)